version: '3.3'

services:
  gateway:
    build:
      context: .
      dockerfile: src/Gateway/Dockerfile
    container_name: ocelot-gateway
    ports:
      - "0.0.0.0:7777:7777"
    environment:
      - ASPNETCORE_URLS=http://+:7777
    depends_on:
      - sales-api
    networks:
      - evaluation-network

  sales-api:
    image: sales-api
    build: 
      context: .
      dockerfile: src/SalesApi/Dockerfile
    container_name: sales-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8080"
    environment:
      - ConnectionStrings__SalesApiDb=Host=db;Database=SalesApiDb;Username=postgres;Password=admin
    networks:
      - evaluation-network
    tty: true

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: SalesApiDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - evaluation-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s      

networks:
  evaluation-network:
    driver: bridge
